### ISSUE TITLE
Splitting of age_gender

### ISSUE THREAD

**Issue by Jon557** [mpomar/Fetscrape#1]
Enhancement.

Great code, works perfectly, I have crafted mine to save to SQL rather than CSV but have added a little extra code that others might like, add this code under the "`age_gender = ...`" to split the age/gender. Then it's just a matter of using the new strings how you like, for example add them to the csv with the others at the bottom of the script.

>         # Capture length of digits (or escape when 4 digits long, prevents infinite loop where gender is omitted)
>         j=1
>         while( age_gender[0:j].isdigit() and j<=4):j+=1
> 
>         # Offset pointer
>         j-=1
>         age = age_gender[0:j]
>         gender = age_gender[j:]

Also add library at the top

> import sys

I'd just like to point out I'm new here, not sure of etiquette :-)

Regards, Jon

**Comment by timmermansjoy** [comment]
for education, you can just do it like 

```py
age_gender = details.split(' ')[0]
age, gender = re.findall(r'(\d+|\D+)', age_gender)
```

more elegant in 2 lines of code

**Comment by mpomar** [comment]
After ages I have finally implemented these changes! Thank you for the input! :-)
